### PR TITLE
Fix deprecation and missing key warnings

### LINKED ISSUE #2: Fix warnings
There are some warnings about some kind of deprecation and missing keys.

### PR DESCRIPTION
**Pull request by reneeleung**
Downgraded `react-native-gesture-handler` to 1.3.0 to fix deprecated use of UI manager.
Added `keyExtractor` to fix missing key warning.

Closes #2

### CODE REVIEW

File: src/components/InstrumentsList.tsx [hunk 1]
```diff
@@ -24,6 +24,7 @@ const InstrumentsList = ({ itemList, navigation }) => {
                     image_url={itemList[item].image_url}
                     navigation={navigation}
                 />}
+                keyExtractor={(_, index) => index.toString()}
```
Comment (allisonchanykei) [inline src/components/InstrumentsList.tsx]: What does this do? lol - both the function and the `keyExtractor`
Can the key be the `item`(basically the id)?

Comment (reneeleung) [reply src/components/InstrumentsList.tsx]: Yup as long as it's unique we can use it as a key, will use `item` instead

Comment (attacker0211) [reply src/components/InstrumentsList.tsx]: WOW YOU GUYS
